import Head from "next/head";
// import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { BsSun } from "react-icons/bs";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h1 className={styles.heading}>Moody Weather</h1>
				<form className={styles.locationForm}>
					<input
						type="text"
						className={styles.locationInput}
						placeholder="Enter town, city or postcode"
					></input>
					<button className={styles.searchButton}>Search</button>
				</form>
				<div className={styles.weatherDisplay}>
					<h2>Today</h2>
					<div className={styles.todayContent}>
						<BsSun />
						<div className={styles.description}>
							<p>Bit of fucking sun but still not fucking warm.</p>
							<p>5°C / 12°C</p>
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
